name: Test payload
on: [deployment_status]

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
    - name: Print GitHub event 🖨
      env:
        GITHUB_EVENT: ${{ toJson(github.event) }}
      run: echo "$GITHUB_EVENT"

    - name: Print GitHub env variables 🖨
      run: npx @bahmutov/print-env GITHUB
    
